require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/**/*
    - test/**/*

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
