require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - bin/**/*
    - vendor/**/*
    - test/**/*

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
